name: 'sales-streamlit-dev'

services:
  app:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    command:
      ["streamlit", "run", "app/main.py"]
    ports:
      - '8501:8501'
    restart: always
    volumes:
      - .:/app