name: 'sales-streamlit-dev'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["streamlit", "run", "app/main.py", "--server.port=8501"]
    restart: always
    ports:
      - '8501:8501'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    