version: '3.8'
name: 'sales-analysis-app'

services:
  app:
    container_name: 'streamlit-app'
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    ports:
      - '8501:8501'
    restart: always
    volumes:
      - .:/app